pipeline {
    agent any

    tools {
        terraform 'terraform'
    }	

    stages {
        stage('inicilizar') {
            steps {
                dir("terraform-test"){
                sh 'terraform init'
                }
            }
        }

        stage('validar') {
            steps {
                dir("terraform-test"){
                sh 'terraform validate'
                }
            }
        }
        stage('lanzar') {
            steps {
                dir("terraform-test"){
                sh 'terraform apply -auto-approve'
                }
            }
        }
        stage('output') {
            steps {
                dir("terraform-test"){
                sh 'terraform output'
                }
            }
        }
    }
}
